# Generated by Django 5.0.6 on 2026-10-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='gradcam_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='treatment_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='trichometry_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='urgency_badge',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='urgency_tier',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
